---
deployment:
  tasks:
    - export DEPLOYPATH=/home/askprrnw/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
